# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Tewodros W. Ayalew
title: Computer Science MSc student in the University of Saskatchewan
email: tewodros.ayalew@usask.ca
website: https://tedywond.github.io/

# Social links
twitter_username: tedywond
github_username:  tedywond
# dribbble_username: jekyll
#facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: tewodros-w-ayalew-7b136652
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Tewodros, and I'm a graduate student in Computer Science studying at the University of Saskatchewan. I've had different experiences working in Computer vision, Deep learning, and Machine learning.

  I am most skilled in: <mark>Computer Vision</mark>, <mark>Image Analysis</mark> and <mark>Deep Learning</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
